#!/bin/bash

docker pull projects.registry.vmware.com/nsx_application_platform/clustering/nsx-cloud-connector-check-nsx-licensing-status-with-lastline-cloud:123-c33a1aa7.bionic
docker pull projects.registry.vmware.com/nsx_application_platform/clustering/nsx-cloud-connector-ssl-tunnel:123-31bb14c6.bionic
docker pull projects.registry.vmware.com/nsx_application_platform/clustering/nsx-cloud-connector-proxy-nginx:123-d24e4997.bionic
docker pull projects.registry.vmware.com/nsx_application_platform/clustering/nsx-cloud-connector-webproxy-tunnel:123-256f91ff.bionic
docker pull projects.registry.vmware.com/nsx_application_platform/clustering/nsx-cloud-connector-register-nsx-to-lastline-cloud:123-c33a1aa7.bionic
docker pull projects.registry.vmware.com/nsx_application_platform/clustering/nsx-cloud-connector-update-nsx-licensing-status-for-lastline-cloud:123-c33a1aa7.bionic
docker pull projects.registry.vmware.com/nsx_application_platform/clustering/third-party/core_collector:19067763
docker pull projects.registry.vmware.com/nsx_application_platform/clustering/context_correlator:19067763
docker pull projects.registry.vmware.com/nsx_application_platform/clustering/recommendation-spark-job:19067763
docker pull projects.registry.vmware.com/nsx_application_platform/clustering/third-party/python-common:19067763
docker pull projects.registry.vmware.com/nsx_application_platform/clustering/data-archiver:19067763
docker pull projects.registry.vmware.com/nsx_application_platform/clustering/data-collection:19067763
docker pull projects.registry.vmware.com/nsx_application_platform/clustering/intelligence-ui:19067763
docker pull projects.registry.vmware.com/nsx_application_platform/clustering/latestflow:19067763
docker pull projects.registry.vmware.com/nsx_application_platform/clustering/llanta-service:719-38dc10b0.bionic
docker pull projects.registry.vmware.com/nsx_application_platform/clustering/llanta-nsxi-job:719-6b7b7175.bionic
docker pull projects.registry.vmware.com/nsx_application_platform/clustering/llqueue-kafka-worker:719-9a708762.bionic
docker pull projects.registry.vmware.com/nsx_application_platform/clustering/feature_switch_watcher:19067759
docker pull projects.registry.vmware.com/nsx_application_platform/clustering/feature_switch_watcher:19067767
docker pull projects.registry.vmware.com/nsx_application_platform/clustering/antimalware-ui:19067767
docker pull projects.registry.vmware.com/nsx_application_platform/clustering/sa-registration-scripts:19067767
docker pull projects.registry.vmware.com/nsx_application_platform/clustering/nsx_config:19067763
docker pull projects.registry.vmware.com/nsx_application_platform/clustering/nsx-cloud-connector-enable-disable-ids-events:123-c33a1aa7.bionic
docker pull projects.registry.vmware.com/nsx_application_platform/clustering/feature_switch_watcher:19067761
docker pull projects.registry.vmware.com/nsx_application_platform/clustering/nsx-cloud-connector-upload-nsx-config-to-lastline-cloud:123-c33a1aa7.bionic
docker pull projects.registry.vmware.com/nsx_application_platform/clustering/nsx-cloud-connector-worker:123-c33a1aa7.bionic
docker pull projects.registry.vmware.com/nsx_application_platform/clustering/hombre:19067763
docker pull projects.registry.vmware.com/nsx_application_platform/clustering/nta_server:19067763
docker pull projects.registry.vmware.com/nsx_application_platform/clustering/pubsub:19067763
docker pull projects.registry.vmware.com/nsx_application_platform/clustering/raw_flow_correlator:19067763
docker pull projects.registry.vmware.com/nsx_application_platform/clustering/recommendation:19067763
docker pull projects.registry.vmware.com/nsx_application_platform/clustering/reputation-service:19067759
docker pull projects.registry.vmware.com/nsx_application_platform/clustering/sa-asds:19067767
docker pull projects.registry.vmware.com/nsx_application_platform/clustering/sa-events-processor:19067767
docker pull projects.registry.vmware.com/nsx_application_platform/clustering/sa-scheduler-services:19067767
docker pull projects.registry.vmware.com/nsx_application_platform/clustering/sa-web-services:19067767
docker pull projects.registry.vmware.com/nsx_application_platform/clustering/over_flow_correlator:19067763
docker pull projects.registry.vmware.com/nsx_application_platform/clustering/spark-job-manager:19067763
docker pull projects.registry.vmware.com/nsx_application_platform/clustering/visualization:19067763
